public with sharing class AttachmentUploadController {
/*
  public Attachment attachment {
  get {
      if (attachment == null)
        attachment = new Attachment();
      return attachment;
    }
  set;
  }

    public PageReference Chargent() {
        ChargentSFA.TChargentOperations.ChargeOpportunity_Click('00628000008jURD');
        return null;
    }
    
  public PageReference upload() {

    attachment.OwnerId = UserInfo.getUserId();
    attachment.ParentId = 'a012800000SdK3i'; // the record the file is attached to
    attachment.IsPrivate = false;
      

    try {
      insert attachment;
    } catch (DMLException e) {
      ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error uploading attachment'));
      return null;
    } finally {
      attachment = new Attachment(); 
    }

    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Attachment uploaded successfully'));
    return null;
  }
*/
}